apiVersion:  apps/v1
kind:  Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  template:
    metadata:
      name: rc-pod1
      labels: 
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80
  replicas:  3
  selector:
    matchLabels:
      app: v1